In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
repo_root = Path(__file__).resolve().parents[1] if "__file__" in globals() else Path.cwd().parents[0]
base_path = repo_root / "data" / "averaged"
print("Base path resolved to:", base_path)
files = list(base_path.glob("**/*_inavg.csv"))
if not files:
    raise FileNotFoundError(f"No *_inavg.csv files found under {base_path}")

# ---- Load participant data ---- #
participant_dfs = {}
for file in files:
    name = file.parent.name
    df = pd.read_csv(file)
    participant_dfs[name] = df

# ---- Build RT matrix ---- #
rt_matrix = []
participant_names = []

for name, df in participant_dfs.items():
    rt_col = [col for col in df.columns if col.lower() != "gap"][0]
    rt_values = df[rt_col].values.squeeze()  # ensure 1D
    rt_matrix.append(rt_values)
    participant_names.append(name + "I")

rt_matrix = np.vstack(rt_matrix) 

print("RT matrix shape:", rt_matrix.shape)

Base path resolved to: /Users/vidhyakshayakannan/Documents/Temporal-Attention/data/averaged
RT matrix shape: (10, 46)

In [3]:
similarity_matrix = cosine_similarity(rt_matrix)
similarity_df = pd.DataFrame(similarity_matrix,
                             index=participant_names,
                             columns=participant_names)

print("Cosine Similarity Matrix (In-Tune Average RTs):")
display(similarity_df.round(4))

Cosine Similarity Matrix (In-Tune Average RTs):

,navyaI,manaswiniI,vidhyaI,mahalakshmiI,addieI,jillI,richardI,angelynI,lilaI,sreeI
navyaI,1.0000,0.9875,0.9801,0.9754,0.9757,0.9859,0.9804,0.9821,0.9834,0.9794
manaswiniI,0.9875,1.0000,0.9939,0.9900,0.9838,0.9952,0.9915,0.9914,0.9912,0.9934
vidhyaI,0.9801,0.9939,1.0000,0.9883,0.9803,0.9907,0.9835,0.9880,0.9873,0.9910
mahalakshmiI,0.9754,0.9900,0.9883,1.0000,0.9775,0.9872,0.9845,0.9886,0.9855,0.9863
addieI,0.9757,0.9838,0.9803,0.9775,1.0000,0.9794,0.9790,0.9759,0.9776,0.9789
jillI,0.9859,0.9952,0.9907,0.9872,0.9794,1.0000,0.9876,0.9914,0.9873,0.9877
richardI,0.9804,0.9915,0.9835,0.9845,0.9790,0.9876,1.0000,0.9868,0.9876,0.9889
angelynI,0.9821,0.9914,0.9880,0.9886,0.9759,0.9914,0.9868,1.0000,0.9909,0.9876
lilaI,0.9834,0.9912,0.9873,0.9855,0.9776,0.9873,0.9876,0.9909,1.0000,0.9853
sreeI,0.9794,0.9934,0.9910,0.9863,0.9789,0.9877,0.9889,0.9876,0.9853,1.0000

In [4]:
difference_matrix = 1- cosine_similarity(rt_matrix)
difference_df = pd.DataFrame(difference_matrix,
                             index=participant_names,
                             columns=participant_names)
display(difference_df.round(4))

,navyaI,manaswiniI,vidhyaI,mahalakshmiI,addieI,jillI,richardI,angelynI,lilaI,sreeI
navyaI,0.0000,0.0125,0.0199,0.0246,0.0243,0.0141,0.0196,0.0179,0.0166,0.0206
manaswiniI,0.0125,0.0000,0.0061,0.0100,0.0162,0.0048,0.0085,0.0086,0.0088,0.0066
vidhyaI,0.0199,0.0061,0.0000,0.0117,0.0197,0.0093,0.0165,0.0120,0.0127,0.0090
mahalakshmiI,0.0246,0.0100,0.0117,-0.0000,0.0225,0.0128,0.0155,0.0114,0.0145,0.0137
addieI,0.0243,0.0162,0.0197,0.0225,0.0000,0.0206,0.0210,0.0241,0.0224,0.0211
jillI,0.0141,0.0048,0.0093,0.0128,0.0206,0.0000,0.0124,0.0086,0.0127,0.0123
richardI,0.0196,0.0085,0.0165,0.0155,0.0210,0.0124,0.0000,0.0132,0.0124,0.0111
angelynI,0.0179,0.0086,0.0120,0.0114,0.0241,0.0086,0.0132,0.0000,0.0091,0.0124
lilaI,0.0166,0.0088,0.0127,0.0145,0.0224,0.0127,0.0124,0.0091,0.0000,0.0147
sreeI,0.0206,0.0066,0.0090,0.0137,0.0211,0.0123,0.0111,0.0124,0.0147,-0.0000

In [5]:
repo_root = Path(__file__).resolve().parents[1] if "__file__" in globals() else Path.cwd().parents[0]
base_path = repo_root / "data" / "averaged"
print("Base path resolved to:", base_path)
files = list(base_path.glob("**/*_outavg.csv"))
if not files:
    raise FileNotFoundError(f"No *_inavg.csv files found under {base_path}")

# ---- Load participant data ---- #
participant_dfs = {}
for file in files:
    name = file.parent.name
    df = pd.read_csv(file)
    participant_dfs[name] = df

# ---- Build RT matrix ---- #
rt_matrix = []
participant_names = []

for name, df in participant_dfs.items():
    rt_col = [col for col in df.columns if col.lower() != "gap"][0]
    rt_values = df[rt_col].values.squeeze()  # ensure 1D
    rt_matrix.append(rt_values)
    participant_names.append(name + "O")

rt_matrix = np.vstack(rt_matrix) 

print("RT matrix shape:", rt_matrix.shape)

Base path resolved to: /Users/vidhyakshayakannan/Documents/Temporal-Attention/data/averaged
RT matrix shape: (10, 46)

In [6]:
similarity_matrix = cosine_similarity(rt_matrix)
similarity_df = pd.DataFrame(similarity_matrix,
                             index=participant_names,
                             columns=participant_names)

print("Cosine Similarity Matrix (Out-of-Tune Average RTs):")
display(similarity_df.round(4))

Cosine Similarity Matrix (Out-of-Tune Average RTs):

,navyaO,manaswiniO,vidhyaO,mahalakshmiO,addieO,jillO,richardO,angelynO,lilaO,sreeO
navyaO,1.0000,0.9869,0.9742,0.9818,0.9727,0.9832,0.9810,0.9870,0.9774,0.9813
manaswiniO,0.9869,1.0000,0.9911,0.9879,0.9815,0.9924,0.9932,0.9942,0.9891,0.9923
vidhyaO,0.9742,0.9911,1.0000,0.9813,0.9789,0.9878,0.9874,0.9869,0.9821,0.9898
mahalakshmiO,0.9818,0.9879,0.9813,1.0000,0.9781,0.9858,0.9865,0.9849,0.9840,0.9861
addieO,0.9727,0.9815,0.9789,0.9781,1.0000,0.9749,0.9759,0.9769,0.9741,0.9794
jillO,0.9832,0.9924,0.9878,0.9858,0.9749,1.0000,0.9926,0.9926,0.9861,0.9912
richardO,0.9810,0.9932,0.9874,0.9865,0.9759,0.9926,1.0000,0.9899,0.9887,0.9896
angelynO,0.9870,0.9942,0.9869,0.9849,0.9769,0.9926,0.9899,1.0000,0.9843,0.9887
lilaO,0.9774,0.9891,0.9821,0.9840,0.9741,0.9861,0.9887,0.9843,1.0000,0.9855
sreeO,0.9813,0.9923,0.9898,0.9861,0.9794,0.9912,0.9896,0.9887,0.9855,1.0000

In [7]:
difference_matrix = 1- cosine_similarity(rt_matrix)
difference_df = pd.DataFrame(difference_matrix,
                             index=participant_names,
                             columns=participant_names)
display(difference_df.round(4))

,navyaO,manaswiniO,vidhyaO,mahalakshmiO,addieO,jillO,richardO,angelynO,lilaO,sreeO
navyaO,0.0000,0.0131,0.0258,0.0182,0.0273,0.0168,0.0190,0.0130,0.0226,0.0187
manaswiniO,0.0131,-0.0000,0.0089,0.0121,0.0185,0.0076,0.0068,0.0058,0.0109,0.0077
vidhyaO,0.0258,0.0089,0.0000,0.0187,0.0211,0.0122,0.0126,0.0131,0.0179,0.0102
mahalakshmiO,0.0182,0.0121,0.0187,0.0000,0.0219,0.0142,0.0135,0.0151,0.0160,0.0139
addieO,0.0273,0.0185,0.0211,0.0219,0.0000,0.0251,0.0241,0.0231,0.0259,0.0206
jillO,0.0168,0.0076,0.0122,0.0142,0.0251,0.0000,0.0074,0.0074,0.0139,0.0088
richardO,0.0190,0.0068,0.0126,0.0135,0.0241,0.0074,0.0000,0.0101,0.0113,0.0104
angelynO,0.0130,0.0058,0.0131,0.0151,0.0231,0.0074,0.0101,0.0000,0.0157,0.0113
lilaO,0.0226,0.0109,0.0179,0.0160,0.0259,0.0139,0.0113,0.0157,-0.0000,0.0145
sreeO,0.0187,0.0077,0.0102,0.0139,0.0206,0.0088,0.0104,0.0113,0.0145,-0.0000

In [8]:
base_path = Path.cwd().parent
averaged_dir = base_path / "data" / "averaged"

# ---- COLLECT PARTICIPANTS ---- #
participants = [f.name for f in averaged_dir.iterdir() if f.is_dir()]
participants.sort()
print(f"Found {len(participants)} participants:", participants)

combined_rt_matrix = []
combined_names = []

# ---- BUILD MATRIX ---- #
for name in participants:
    participant_dir = averaged_dir / name
    in_file = participant_dir / f"{name}_inavg.csv"
    out_file = participant_dir / f"{name}_outavg.csv"
    
    if not in_file.exists() or not out_file.exists():
        continue
    
    try:
        in_df = pd.read_csv(in_file)
        out_df = pd.read_csv(out_file)
    except Exception as e:
        continue
    
    # Identify RT columns dynamically
    in_col = next((col for col in in_df.columns if "InAveRT" in col), None)
    out_col = next((col for col in out_df.columns if "OutAveRT" in col), None)
    
    if not in_col or not out_col:
        continue
    
    in_rt = in_df[in_col].values
    out_rt = out_df[out_col].values

    combined_rt_matrix.append(in_rt)
    combined_names.append(name.title() + "_In")

    combined_rt_matrix.append(out_rt)
    combined_names.append(name.title() + "_Out")

# ---- CONVERT TO NUMPY ---- #
combined_rt_matrix = np.vstack(combined_rt_matrix)
print(f"\nRT matrix shape: {combined_rt_matrix.shape}")

# ---- COSINE SIMILARITY ---- #
similarity_matrix = cosine_similarity(combined_rt_matrix)

combined_similarity_df = pd.DataFrame(similarity_matrix, index=combined_names, columns=combined_names)
print("\nCosine Similarity Matrix (In-Tune & Out-of-Tune Combined):")
display(combined_similarity_df.round(3))

Found 12 participants: ['addie', 'all_combined', 'angelyn', 'combined', 'jill', 'lila', 'mahalakshmi', 'manaswini', 'navya', 'richard', 'sree', 'vidhya']

RT matrix shape: (20, 46)

Cosine Similarity Matrix (In-Tune & Out-of-Tune Combined):

,Addie_In,Addie_Out,Angelyn_In,Angelyn_Out,Jill_In,Jill_Out,Lila_In,Lila_Out,Mahalakshmi_In,Mahalakshmi_Out,Manaswini_In,Manaswini_Out,Navya_In,Navya_Out,Richard_In,Richard_Out,Sree_In,Sree_Out,Vidhya_In,Vidhya_Out
Addie_In,1.000,0.969,0.976,0.987,0.979,0.986,0.978,0.979,0.977,0.976,0.984,0.982,0.976,0.973,0.979,0.980,0.979,0.983,0.980,0.977
Addie_Out,0.969,1.000,0.978,0.977,0.977,0.975,0.986,0.974,0.977,0.978,0.979,0.982,0.969,0.973,0.975,0.976,0.974,0.979,0.973,0.979
Angelyn_In,0.976,0.978,1.000,0.990,0.991,0.988,0.991,0.982,0.989,0.983,0.991,0.994,0.982,0.983,0.987,0.988,0.988,0.992,0.988,0.989
Angelyn_Out,0.987,0.977,0.990,1.000,0.990,0.993,0.989,0.984,0.990,0.985,0.994,0.994,0.980,0.987,0.988,0.990,0.989,0.989,0.993,0.987
Jill_In,0.979,0.977,0.991,0.990,1.000,0.990,0.987,0.990,0.987,0.985,0.995,0.994,0.986,0.982,0.988,0.988,0.988,0.988,0.991,0.987
Jill_Out,0.986,0.975,0.988,0.993,0.990,1.000,0.989,0.986,0.989,0.986,0.994,0.992,0.979,0.983,0.989,0.993,0.989,0.991,0.990,0.988
Lila_In,0.978,0.986,0.991,0.989,0.987,0.989,1.000,0.985,0.985,0.986,0.991,0.993,0.983,0.984,0.988,0.990,0.985,0.990,0.987,0.985
Lila_Out,0.979,0.974,0.982,0.984,0.990,0.986,0.985,1.000,0.982,0.984,0.990,0.989,0.977,0.977,0.985,0.989,0.988,0.986,0.985,0.982
Mahalakshmi_In,0.977,0.977,0.989,0.990,0.987,0.989,0.985,0.982,1.000,0.985,0.990,0.991,0.975,0.984,0.984,0.987,0.986,0.990,0.988,0.987
Mahalakshmi_Out,0.976,0.978,0.983,0.985,0.985,0.986,0.986,0.984,0.985,1.000,0.990,0.988,0.979,0.982,0.982,0.986,0.988,0.986,0.987,0.981
Manaswini_In,0.984,0.979,0.991,0.994,0.995,0.994,0.991,0.990,0.990,0.990,1.000,0.998,0.987,0.986,0.991,0.993,0.993,0.991,0.994,0.989
Manaswini_Out,0.982,0.982,0.994,0.994,0.994,0.992,0.993,0.989,0.991,0.988,0.998,1.000,0.985,0.987,0.992,0.993,0.993,0.992,0.993,0.991
Navya_In,0.976,0.969,0.982,0.980,0.986,0.979,0.983,0.977,0.975,0.979,0.987,0.985,1.000,0.972,0.980,0.982,0.979,0.981,0.980,0.977
Navya_Out,0.973,0.973,0.983,0.987,0.982,0.983,0.984,0.977,0.984,0.982,0.986,0.987,0.972,1.000,0.976,0.981,0.975,0.981,0.982,0.974
Richard_In,0.979,0.975,0.987,0.988,0.988,0.989,0.988,0.985,0.984,0.982,0.991,0.992,0.980,0.976,1.000,0.989,0.989,0.984,0.983,0.985
Richard_Out,0.980,0.976,0.988,0.990,0.988,0.993,0.990,0.989,0.987,0.986,0.993,0.993,0.982,0.981,0.989,1.000,0.989,0.990,0.989,0.987
Sree_In,0.979,0.974,0.988,0.989,0.988,0.989,0.985,0.988,0.986,0.988,0.993,0.993,0.979,0.975,0.989,0.989,1.000,0.987,0.991,0.988
Sree_Out,0.983,0.979,0.992,0.989,0.988,0.991,0.990,0.986,0.990,0.986,0.991,0.992,0.981,0.981,0.984,0.990,0.987,1.000,0.986,0.990
Vidhya_In,0.980,0.973,0.988,0.993,0.991,0.990,0.987,0.985,0.988,0.987,0.994,0.993,0.980,0.982,0.983,0.989,0.991,0.986,1.000,0.987
Vidhya_Out,0.977,0.979,0.989,0.987,0.987,0.988,0.985,0.982,0.987,0.981,0.989,0.991,0.977,0.974,0.985,0.987,0.988,0.990,0.987,1.000

In [9]:
combined_rt_matrix = []
combined_names = []

# ---- BUILD MATRIX ---- #
for name in participants:
    participant_dir = averaged_dir / name
    in_file = participant_dir / f"{name}_inavg.csv"
    out_file = participant_dir / f"{name}_outavg.csv"
    
    if not in_file.exists() or not out_file.exists():
        continue
    
    try:
        in_df = pd.read_csv(in_file)
        out_df = pd.read_csv(out_file)
    except Exception as e:
        continue
    
    # Identify RT columns dynamically
    in_col = next((col for col in in_df.columns if "InAveRT" in col), None)
    out_col = next((col for col in out_df.columns if "OutAveRT" in col), None)
    
    if not in_col or not out_col:
        continue
    
    in_rt = in_df[in_col].values
    out_rt = out_df[out_col].values

    combined_rt_matrix.append(in_rt)
    combined_names.append(name.title() + "_In")

    combined_rt_matrix.append(out_rt)
    combined_names.append(name.title() + "_Out")

# ---- CONVERT TO NUMPY ---- #
combined_rt_matrix = np.vstack(combined_rt_matrix)
print(f"\nRT matrix shape: {combined_rt_matrix.shape}")

RT matrix shape: (20, 46)

### Cosine Distance

In [10]:
difference_matrix = 1 - cosine_similarity(combined_rt_matrix)

combined_difference_df = pd.DataFrame(difference_matrix, index=combined_names, columns=combined_names)
print("\nCosine Distance Matrix (In-Tune & Out-of-Tune Combined):")
display(combined_similarity_df.round(3))

Cosine Distance Matrix (In-Tune & Out-of-Tune Combined):

,Addie_In,Addie_Out,Angelyn_In,Angelyn_Out,Jill_In,Jill_Out,Lila_In,Lila_Out,Mahalakshmi_In,Mahalakshmi_Out,Manaswini_In,Manaswini_Out,Navya_In,Navya_Out,Richard_In,Richard_Out,Sree_In,Sree_Out,Vidhya_In,Vidhya_Out
Addie_In,1.000,0.969,0.976,0.987,0.979,0.986,0.978,0.979,0.977,0.976,0.984,0.982,0.976,0.973,0.979,0.980,0.979,0.983,0.980,0.977
Addie_Out,0.969,1.000,0.978,0.977,0.977,0.975,0.986,0.974,0.977,0.978,0.979,0.982,0.969,0.973,0.975,0.976,0.974,0.979,0.973,0.979
Angelyn_In,0.976,0.978,1.000,0.990,0.991,0.988,0.991,0.982,0.989,0.983,0.991,0.994,0.982,0.983,0.987,0.988,0.988,0.992,0.988,0.989
Angelyn_Out,0.987,0.977,0.990,1.000,0.990,0.993,0.989,0.984,0.990,0.985,0.994,0.994,0.980,0.987,0.988,0.990,0.989,0.989,0.993,0.987
Jill_In,0.979,0.977,0.991,0.990,1.000,0.990,0.987,0.990,0.987,0.985,0.995,0.994,0.986,0.982,0.988,0.988,0.988,0.988,0.991,0.987
Jill_Out,0.986,0.975,0.988,0.993,0.990,1.000,0.989,0.986,0.989,0.986,0.994,0.992,0.979,0.983,0.989,0.993,0.989,0.991,0.990,0.988
Lila_In,0.978,0.986,0.991,0.989,0.987,0.989,1.000,0.985,0.985,0.986,0.991,0.993,0.983,0.984,0.988,0.990,0.985,0.990,0.987,0.985
Lila_Out,0.979,0.974,0.982,0.984,0.990,0.986,0.985,1.000,0.982,0.984,0.990,0.989,0.977,0.977,0.985,0.989,0.988,0.986,0.985,0.982
Mahalakshmi_In,0.977,0.977,0.989,0.990,0.987,0.989,0.985,0.982,1.000,0.985,0.990,0.991,0.975,0.984,0.984,0.987,0.986,0.990,0.988,0.987
Mahalakshmi_Out,0.976,0.978,0.983,0.985,0.985,0.986,0.986,0.984,0.985,1.000,0.990,0.988,0.979,0.982,0.982,0.986,0.988,0.986,0.987,0.981
Manaswini_In,0.984,0.979,0.991,0.994,0.995,0.994,0.991,0.990,0.990,0.990,1.000,0.998,0.987,0.986,0.991,0.993,0.993,0.991,0.994,0.989
Manaswini_Out,0.982,0.982,0.994,0.994,0.994,0.992,0.993,0.989,0.991,0.988,0.998,1.000,0.985,0.987,0.992,0.993,0.993,0.992,0.993,0.991
Navya_In,0.976,0.969,0.982,0.980,0.986,0.979,0.983,0.977,0.975,0.979,0.987,0.985,1.000,0.972,0.980,0.982,0.979,0.981,0.980,0.977
Navya_Out,0.973,0.973,0.983,0.987,0.982,0.983,0.984,0.977,0.984,0.982,0.986,0.987,0.972,1.000,0.976,0.981,0.975,0.981,0.982,0.974
Richard_In,0.979,0.975,0.987,0.988,0.988,0.989,0.988,0.985,0.984,0.982,0.991,0.992,0.980,0.976,1.000,0.989,0.989,0.984,0.983,0.985
Richard_Out,0.980,0.976,0.988,0.990,0.988,0.993,0.990,0.989,0.987,0.986,0.993,0.993,0.982,0.981,0.989,1.000,0.989,0.990,0.989,0.987
Sree_In,0.979,0.974,0.988,0.989,0.988,0.989,0.985,0.988,0.986,0.988,0.993,0.993,0.979,0.975,0.989,0.989,1.000,0.987,0.991,0.988
Sree_Out,0.983,0.979,0.992,0.989,0.988,0.991,0.990,0.986,0.990,0.986,0.991,0.992,0.981,0.981,0.984,0.990,0.987,1.000,0.986,0.990
Vidhya_In,0.980,0.973,0.988,0.993,0.991,0.990,0.987,0.985,0.988,0.987,0.994,0.993,0.980,0.982,0.983,0.989,0.991,0.986,1.000,0.987
Vidhya_Out,0.977,0.979,0.989,0.987,0.987,0.988,0.985,0.982,0.987,0.981,0.989,0.991,0.977,0.974,0.985,0.987,0.988,0.990,0.987,1.000